name: C/C++ CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: comua/aerobus-open-source:build-1.3
    steps:
    - uses: actions/checkout@v4
    - name: cppcheck
      if: success()
      run: cppcheck --std=c++20 --language=c++ src/aerobus.h && cppcheck --std=c++20 --language=c++ src/lib_tests.cpp
    - name: cpplint
      if: success()
      run: cpplint src/lib.h && cpplint src/lib_tests.cpp
    - name: test
      if: success()
      run: make clean tests
    - name: documentation
      if: success()
      run: make doc
    - name: paper
      if: success()
      run: make clean paper
